NAME="Claude"
API_URL="https://api.anthropic.com/v1/messages"
API_KEY=""
MODEL="claude-haiku-4-5-20251001"
MODELS="claude-haiku-4-5-20251001,claude-sonnet-4-5-20250929,claude-opus-4-5-20251101"
MAX_TOKENS=8000
