NAME="Gemini"
API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent"
API_KEY="AIzaSyD8GJKx20_QlQuqCLsHVa7FGXyAoe2FVDM"
MODEL="gemini-2.5-flash"
MODELS="gemini-2.5-pro,gemini-2.5-flash,gemini-2.5-flash-lite"
MODEL_INFOS="gemini-2.5-pro:En Zeki. Karmaşık kod ve mantık için. $2/1M input, $12/1M output|gemini-2.5-flash:Hız ve Zeka Dengesi. Botlar için ideal. $0.50/1M input, $3/1M output|gemini-2.5-flash-lite:En Hızlı ve En Ucuz. Basit seri işler için. $0.10/1M input, $0.40/1M output"
MAX_TOKENS=8000
