NAME="Gemini"
API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro:generateContent"
API_KEY=""
MODEL="gemini-3.1-pro"
MODELS="gemini-3.1-pro,gemini-3.1-flash,gemini-3.1-flash-lite"
MODEL_INFOS="gemini-3.1-pro:En Zeki (Claude Rakibi). Karmaşık kod ve mantık için. $2/1M input, $12/1M output|gemini-3.1-flash:Hız ve Zeka Dengesi. Botlar için ideal. $0.50/1M input, $3/1M output|gemini-3.1-flash-lite:En Hızlı ve En Ucuz. Basit seri işler için. $0.25/1M input, $1.50/1M output"
MAX_TOKENS=8000
